#!/usr/bin/env python3
"""
sync-model-policy.py — single source of truth for sub-agent model + effort.

Reads `.claude/model-policy.yaml` (per-repo `assignments` + `flag_overrides`,
which `extends:` the shared parent `.claude/model-policy.tiers.yaml` for tier
definitions) and stamps `model:` / `effort:` into every `.claude/agents/*.md`
frontmatter. Reasoning TIERS are the placeholder abstraction: edit a tier's
model/effort in ONE file and re-sync to re-stamp the whole fleet (e.g. swap the
deep-reasoning tier between `opus` and `fable`).

The script ONLY ever touches the `model:` and `effort:` frontmatter lines of
agent files, and the text between `<!-- BEGIN MODEL-POLICY --> ... <!-- END
MODEL-POLICY -->` markers in command files. It never edits free prose, tools,
memory, or descriptions.

Modes
  (default)    stamp frontmatter + regenerate command marker tables, in place
  --dry-run    print the unified diff that WOULD be written; change nothing
  --check      CI drift gate: exit 1 (+diff) if on-disk != resolved; also runs
               closed-vocab validation. Exit 0 when clean.
  --init       bootstrap a `model-policy.yaml` from CURRENT agent frontmatter
               (opus->deep, sonnet->standard, haiku->fast) so the first sync is
               byte-equivalent. Prints to stdout; redirect to the policy file.

Usage
  python .claude/scripts/sync-model-policy.py
  python .claude/scripts/sync-model-policy.py --check
  python .claude/scripts/sync-model-policy.py --dry-run
  python .claude/scripts/sync-model-policy.py --init > .claude/model-policy.yaml

Cross-platform: pure stdlib + PyYAML; writes LF line endings to avoid CRLF
churn poisoning --check diffs on Windows.
"""

from __future__ import annotations

import argparse
import difflib
import pathlib
import re
import sys

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.stderr.write(
        "sync-model-policy.py requires PyYAML. Install with: pip install pyyaml\n"
    )
    sys.exit(2)

# Windows consoles default to cp1252, but agent bodies carry UTF-8 (arrows, em
# dashes). Without this, printing a unified diff raises UnicodeEncodeError partway
# through and silently truncates the drift list while still exiting non-zero.
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

# Script lives at <repo>/.claude/scripts/sync-model-policy.py
REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent.parent
AGENTS_DIR = REPO_ROOT / ".claude" / "agents"
COMMANDS_DIR = REPO_ROOT / ".claude" / "commands"
POLICY_PATH = REPO_ROOT / ".claude" / "model-policy.yaml"

# Closed vocabularies (kept in lockstep with check_agent_metadata.py)
VALID_MODELS = {"haiku", "sonnet", "opus", "fable", "inherit"}
VALID_EFFORT = {"low", "medium", "high", "xhigh", "max"}

# Which effort levels each model alias actually accepts. Haiku rejects the
# effort parameter entirely; xhigh/max are Opus-4.8 / Fable-5 territory; Sonnet
# 4.6 tops out at `max` but xhigh is unconfirmed there, so it is excluded to
# stay safe. The stamper drops effort to a supported fallback (or omits the
# line) rather than ever writing an effort a model would reject.
EFFORT_SUPPORT = {
    "haiku": set(),  # no effort control -> never stamp an effort: line
    "sonnet": {"low", "medium", "high", "max"},
    "opus": {"low", "medium", "high", "xhigh", "max"},
    "fable": {"low", "medium", "high", "xhigh", "max"},
    "inherit": set(),
}

MARKER_BEGIN = "<!-- BEGIN MODEL-POLICY (generated by sync-model-policy.py — do not edit by hand) -->"
MARKER_END = "<!-- END MODEL-POLICY -->"

FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---", re.DOTALL)


# --------------------------------------------------------------------------- #
# Policy loading + resolution
# --------------------------------------------------------------------------- #
def load_policy() -> dict:
    """Load the per-repo policy and merge in the parent tier definitions."""
    if not POLICY_PATH.is_file():
        sys.stderr.write(f"ERROR: policy file not found: {POLICY_PATH}\n")
        sys.exit(2)
    policy = yaml.safe_load(POLICY_PATH.read_text(encoding="utf-8")) or {}

    tiers: dict = {}
    extends = policy.get("extends")
    if extends:
        parent_path = (POLICY_PATH.parent / extends).resolve()
        if not parent_path.is_file():
            sys.stderr.write(f"ERROR: extends target not found: {parent_path}\n")
            sys.exit(2)
        parent = yaml.safe_load(parent_path.read_text(encoding="utf-8")) or {}
        tiers = dict(parent.get("tiers", {}))
    # A repo MAY locally override individual tiers (rare).
    for name, spec in (policy.get("tier_overrides") or {}).items():
        tiers[name] = {**tiers.get(name, {}), **spec}
    if "tiers" in policy:  # a stray inline tiers block = a silent fork
        sys.stderr.write(
            "WARNING: this repo's model-policy.yaml defines an inline `tiers:` "
            "block; tiers should live in the shared parent file via `extends:`. "
            "Use `tier_overrides:` for deliberate per-repo deviations.\n"
        )
        for name, spec in policy["tiers"].items():
            tiers[name] = {**tiers.get(name, {}), **spec}

    policy["_tiers"] = tiers
    return policy


def resolve_tier(tier_name: str, tiers: dict) -> tuple[str, str | None]:
    """Resolve a tier name to a concrete (model_alias, effort_or_None)."""
    spec = tiers.get(tier_name)
    if spec is None:
        raise KeyError(f"unknown tier '{tier_name}' (defined tiers: {sorted(tiers)})")
    model = spec.get("model", "inherit")
    effort = spec.get("effort")
    fallback = spec.get("fallback_effort")
    supported = EFFORT_SUPPORT.get(model, set())
    if effort is not None and effort not in supported:
        # Requested effort isn't valid for this model -> try fallback, else drop.
        effort = fallback if (fallback in supported) else None
    return model, effort


def tier_for_agent(stem: str, policy: dict) -> str:
    agents = (policy.get("assignments") or {}).get("agents") or {}
    default = (policy.get("assignments") or {}).get("unmapped_default", "standard")
    return agents.get(stem, default)


# --------------------------------------------------------------------------- #
# Frontmatter stamping (touches only model: / effort: lines)
# --------------------------------------------------------------------------- #
def stamp_frontmatter(text: str, model: str, effort: str | None) -> str:
    """Return `text` with model:/effort: frontmatter lines set. No other bytes move."""
    m = FRONTMATTER_RE.match(text)
    if not m:
        return text  # not an agent file with frontmatter; leave untouched
    inner = m.group(1)
    lines = inner.split("\n")

    model_idx = None
    effort_idx = None
    for i, line in enumerate(lines):
        if re.match(r"^model:\s*", line):
            model_idx = i
        elif re.match(r"^effort:\s*", line):
            effort_idx = i

    # model: — update in place, or insert before `memory:` / at end of block.
    if model_idx is not None:
        lines[model_idx] = f"model: {model}"
    else:
        insert_at = len(lines)
        for i, line in enumerate(lines):
            if re.match(r"^memory:\s*", line):
                insert_at = i
                break
        lines.insert(insert_at, f"model: {model}")
        if effort_idx is not None and effort_idx >= insert_at:
            effort_idx += 1
        model_idx = insert_at

    # effort: — set, update, or remove.
    if effort is None:
        if effort_idx is not None:
            del lines[effort_idx]
    else:
        if effort_idx is not None:
            lines[effort_idx] = f"effort: {effort}"
        else:
            lines.insert(model_idx + 1, f"effort: {effort}")

    new_inner = "\n".join(lines)
    return f"---\n{new_inner}\n---" + text[m.end():]


# --------------------------------------------------------------------------- #
# Command marker-table regeneration (only between BEGIN/END markers)
# --------------------------------------------------------------------------- #
def render_command_table(command_name: str, policy: dict) -> str:
    """Build the generated MODEL-POLICY table for one command, or '' if unmapped."""
    tiers = policy["_tiers"]
    commands = (policy.get("assignments") or {}).get("commands") or {}
    flag_overrides = (policy.get("flag_overrides") or {}).get(command_name) or {}
    phases = {
        key.split(":", 1)[1]: tier
        for key, tier in commands.items()
        if key.startswith(command_name + ":")
    }
    if not phases:
        return ""

    # Build reverse map phase -> [(flag, override_tier)]
    phase_flags: dict[str, list[str]] = {}
    for flag, remap in flag_overrides.items():
        for phase, tier in (remap or {}).items():
            model, effort = resolve_tier(tier, tiers)
            eff = f", {effort}" if effort else ""
            phase_flags.setdefault(phase, []).append(f"`{flag}` → {tier} ({model}{eff})")

    rows = ["| Phase | Tier | Model | Effort | With flags |", "|---|---|---|---|---|"]
    for phase, tier in phases.items():
        model, effort = resolve_tier(tier, tiers)
        flags = "; ".join(phase_flags.get(phase, [])) or "—"
        rows.append(f"| {phase} | {tier} | {model} | {effort or '—'} | {flags} |")

    deep = tiers.get("deep", {})
    note = (
        f"\n> Models resolve from `.claude/model-policy.yaml` tiers (deep = "
        f"`{deep.get('model', '?')}`, effort `{deep.get('effort', '—')}`). "
        f"Dispatch each phase with the model + effort shown above. To swap the "
        f"deep tier (Opus 4.8 ↔ Fable 5) edit `.claude/model-policy.tiers.yaml` "
        f"and re-run `sync-model-policy.py`."
    )
    return "\n".join(rows) + "\n" + note


def stamp_command(text: str, command_name: str, policy: dict) -> str:
    """Regenerate the marker block in a command file, if one exists."""
    if MARKER_BEGIN not in text or MARKER_END not in text:
        return text  # not yet migrated; leave untouched
    table = render_command_table(command_name, policy)
    block = f"{MARKER_BEGIN}\n{table}\n{MARKER_END}"
    pattern = re.compile(
        re.escape(MARKER_BEGIN) + r".*?" + re.escape(MARKER_END), re.DOTALL
    )
    return pattern.sub(lambda _: block, text)


# --------------------------------------------------------------------------- #
# Validation
# --------------------------------------------------------------------------- #
def validate(policy: dict) -> list[str]:
    errs: list[str] = []
    tiers = policy["_tiers"]
    if not tiers:
        errs.append("no tiers defined (check `extends:` and the parent tiers file)")
    for name, spec in tiers.items():
        model = spec.get("model", "inherit")
        if model not in VALID_MODELS:
            errs.append(f"tier '{name}': model '{model}' not in {sorted(VALID_MODELS)}")
        eff = spec.get("effort")
        if eff is not None and eff not in VALID_EFFORT:
            errs.append(f"tier '{name}': effort '{eff}' not in {sorted(VALID_EFFORT)}")
    # Every agent on disk must resolve to a known tier.
    for f in sorted(AGENTS_DIR.glob("*.md")):
        tier = tier_for_agent(f.stem, policy)
        if tier not in tiers:
            errs.append(f"agent '{f.stem}' maps to undefined tier '{tier}'")
    # Command-phase keys must reference real command files.
    commands = (policy.get("assignments") or {}).get("commands") or {}
    cmd_names = {p.stem for p in COMMANDS_DIR.glob("*.md")} if COMMANDS_DIR.is_dir() else set()
    for key in commands:
        cname = key.split(":", 1)[0]
        if cmd_names and cname not in cmd_names:
            errs.append(f"command-phase '{key}' references missing command '{cname}.md'")
    return errs


# --------------------------------------------------------------------------- #
# Planning: compute desired bytes for every file
# --------------------------------------------------------------------------- #
def plan(policy: dict) -> dict[pathlib.Path, tuple[str, str]]:
    """Return {path: (current_text, desired_text)} for files that would change."""
    changes: dict[pathlib.Path, tuple[str, str]] = {}
    tiers = policy["_tiers"]

    for f in sorted(AGENTS_DIR.glob("*.md")):
        cur = f.read_text(encoding="utf-8")
        model, effort = resolve_tier(tier_for_agent(f.stem, policy), tiers)
        new = stamp_frontmatter(cur, model, effort)
        if new != cur:
            changes[f] = (cur, new)

    if COMMANDS_DIR.is_dir():
        for f in sorted(COMMANDS_DIR.glob("*.md")):
            cur = f.read_text(encoding="utf-8")
            new = stamp_command(cur, f.stem, policy)
            if new != cur:
                changes[f] = (cur, new)
    return changes


def unified(path: pathlib.Path, cur: str, new: str) -> str:
    rel = path.relative_to(REPO_ROOT).as_posix()
    return "".join(
        difflib.unified_diff(
            cur.splitlines(keepends=True),
            new.splitlines(keepends=True),
            fromfile=f"a/{rel}",
            tofile=f"b/{rel}",
        )
    )


# --------------------------------------------------------------------------- #
# --init bootstrap
# --------------------------------------------------------------------------- #
def emit_init() -> str:
    """Generate a baseline policy mirroring current frontmatter models exactly."""
    model_to_tier = {"opus": "deep", "sonnet": "standard", "haiku": "fast"}
    rows: list[str] = []
    for f in sorted(AGENTS_DIR.glob("*.md")):
        fm = FRONTMATTER_RE.match(f.read_text(encoding="utf-8"))
        model = "sonnet"
        if fm:
            mm = re.search(r"^model:\s*(\S+)", fm.group(1), re.MULTILINE)
            if mm:
                model = mm.group(1)
        rows.append(f"    {f.stem}: {model_to_tier.get(model, 'standard')}")
    repo = REPO_ROOT.name
    body = "\n".join(rows)
    return f"""\
# .claude/model-policy.yaml -- model + effort policy for {repo}
# Tier DEFINITIONS live in the shared parent file (one place to swap Opus<->Fable
# or raise effort fleet-wide). This file maps each agent + command-phase to a tier.
# Edit, then:  python .claude/scripts/sync-model-policy.py
# CI drift gate: python .claude/scripts/sync-model-policy.py --check
schema_version: 1
extends: ../../.claude/model-policy.tiers.yaml

assignments:
  # agent stem -> tier  (bootstrapped from current frontmatter; reclassify per
  # MODEL-EFFORT-CROSS-ANALYSIS.md sec.4 -- e.g. *-challenger / synthesize -> deep,
  # *-querier / *-extractor -> fast)
  agents:
{body}

  # command:phase -> tier (drives the generated MODEL-POLICY table in each
  # command file; only injected where the BEGIN/END markers are present)
  commands: {{}}

  # tier applied to any agent file present on disk but absent from `agents:`
  unmapped_default: standard

# How CLI flags re-map a phase's tier at dispatch (declarative; rendered into
# the command table's "With flags" column).
flag_overrides: {{}}
"""


# --------------------------------------------------------------------------- #
def main() -> int:
    ap = argparse.ArgumentParser(description="Sync model+effort policy into agent/command files")
    ap.add_argument("--check", action="store_true", help="CI drift gate: exit 1 on drift")
    ap.add_argument("--dry-run", action="store_true", help="print diff, write nothing")
    ap.add_argument("--init", action="store_true", help="emit a baseline policy from current frontmatter")
    args = ap.parse_args()

    if not AGENTS_DIR.is_dir():
        sys.stderr.write(f"ERROR: agents dir not found: {AGENTS_DIR}\n")
        return 2

    if args.init:
        sys.stdout.write(emit_init())
        return 0

    policy = load_policy()

    errs = validate(policy)
    if errs:
        sys.stderr.write("POLICY VALIDATION FAILED:\n")
        for e in errs:
            sys.stderr.write(f"  - {e}\n")
        return 1

    changes = plan(policy)

    if args.check:
        if not changes:
            print("model-policy: clean (no drift)")
            return 0
        print(f"model-policy: DRIFT in {len(changes)} file(s):")
        for path, (cur, new) in changes.items():
            print(unified(path, cur, new))
        return 1

    if args.dry_run:
        if not changes:
            print("model-policy: nothing to change")
            return 0
        for path, (cur, new) in changes.items():
            print(unified(path, cur, new))
        print(f"\n[dry-run] {len(changes)} file(s) would change")
        return 0

    for path, (_cur, new) in changes.items():
        path.write_text(new, encoding="utf-8", newline="\n")
    print(f"model-policy: stamped {len(changes)} file(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
